### ISSUE TITLE
Firing a RPCRequest fails

### ISSUE THREAD

**Issue by sev73** [eventEmitter/ee-soa-rpc-request#3]
The code

```js
.then(function(ormResult) {
    var r = new this.Request({
        select: '*'
    });
    var promise = r.send('entity');
    return promise;
}.bind(this)).then(function(status, rpcResult) {
    callback(null, rpcResult);
}).catch(function(error) {
    callback(error);
});
```

does not work.

With this approach the argument ```callback``` of the ```_handleRequest(...)``` function in the
```DefaultService.js``` file is a response object instead of a function. Therefore the program crashes at

https://github.com/eventEmitter/ee-soa-service/blob/master/lib/DefaultService.js#L342

In addition, we believe that the code block at

https://github.com/eventEmitter/ee-soa-rpc-request/blob/master/lib/RCPRequest.js#L105

is incorrect. Replacing it with this code block may help:

```js
callback = function(statusCode, data) {
    if (statusCode !== 1 && statusCode !== 2) rejectPromise(statusCode);
    else resolvePromise(statusCode, data);
};
```

**Comment by eventEmitter** [comment]
thanks for the fix on line 105

this implementation was never tested using a service, i will have to implement this functionality.
